### ISSUE TITLE
[Feature Request] Wind Controls

### ISSUE THREAD

**Issue by meson1** [krikienoid/flagwaver#1]
Flag waver is great and all, but the wind you simulate swings around a lot and varies in strength.

The feature suggestion here is to add controls so the user can customise the wind they want.  So blowing from a particular direction and at a certain strength.

**Comment by aneudysamparo** [comment]
Siting @meson1 How do we can control wind?

Thank you btw!

**Comment by loderunner** [comment]
I added a knob to control wind direction. Check out my fork [here](https://loderunner.github.io/flagwaver/)

The Pull Request is [here](https://github.com/krikienoid/flagwaver/pull/2)

**Comment by flaglover** [comment]
@loderunner this version is great, but I would love new features along with wind direction, like...

1. Ability to select how many flag poles on 1 screen (Limit can be 500 flagpoles)

2. Ability to raise and lower the flags (You set a timer by saying (Example: 2m 2s) and then start the timer to start raising or lowering the flags)(you can choose which to do; raise or lower)

3. Ability to select wind speed (Just type in (Example: 15 mph / kph) and press GO to set new wind speed.)

4. Attach a URL or file to select background (Same as the bar to put in your flag's Url or file)

Thanks for seeing this and I hope to see these features become reality!

**Comment by BenLeggiero** [comment]
Seems like 2.0.0 implemented this!! Yay!

**Comment by krikienoid** [comment]
Finally closing this since updated FlagWaver now features wind controls.

**Comment by TNTGaming25** [comment]
how to download as gif file?

**Comment by BenLeggiero** [comment]
@TNTGaming25 you can [file a new issue](https://github.com/krikienoid/flagwaver/issues/new/choose) for that question 🙂
