### ISSUE TITLE
Load a flag by local file using js code

### ISSUE THREAD

**Issue by duainsulch** [krikienoid/flagwaver#12]
Thanks for your reply, as you point i open the issue here. I want to load a flag from a local file on my computer but using js code instead the button, can you help me? thanks a lot.

**Comment by krikienoid** [comment]
I am not sure what exactly you are trying to do, but JavaScript running in a browser is forbidden from accessing the file system directly. This is a limitation built into browsers for security reasons.

https://stackoverflow.com/questions/41849745/how-to-read-local-files-using-html-5-filereader

**Comment by duainsulch** [comment]
I want to load a flag for a player selected on a checkbox using a webpage for OBS, i can load the image from an URL anyway, but i don´t know how to load the flag by code

**Comment by BenLeggiero** [comment]
@duainsulch So loading by URL is okay too?

**Comment by duainsulch** [comment]
i dont know how to do that by code, i fill the textbox and simulate the click on the button but don´t load the new flag

**Comment by krikienoid** [comment]
What's the URL for the flag?

**Comment by duainsulch** [comment]
http://ageofempires.eu5.org/banderas/paises/es.png

**Comment by krikienoid** [comment]
The first flag works for me. Does this link work for you? https://krikienoid.github.io/flagwaver/#?src=http%3A%2F%2Fageofempires.eu5.org%2Fbanderas%2Fpaises%2Fes.

**Comment by duainsulch** [comment]
Yes, it works. 
A "green screen" background will be great for make it transparent with OBS

**Comment by duainsulch** [comment]
and "blue screen" background for some green flags
