### ISSUE TITLE
Feature request: Support multiple flags

### ISSUE THREAD

**Issue by TonicArtos** [krikienoid/flagwaver#19]
It would be nice to be able to show multiple flags in a line.

**Comment by VVL99** [comment]
http://vvl99.narod.ru/flag3/f10xn.html

**Comment by VVL99** [comment]
`<style>
html, body, span, iframe {
	padding: 0;
	margin: 0;
	border: none;
	background: rgb(86, 108, 115)
}
span {
    width: 33.3%;
	height: 100%;
	display: inline-block;
	border: none;
	padding: 0;
	margin: 0
}
iframe {
    width: 100%;
	height: 100%;
	display: inline-block;
	border: none;
	padding: 0;
	margin: 0
}
</style>
<span><iframe src="http://vvl99.narod.ru/flag3/index.html"></iframe></span><span><iframe src="http://vvl99.narod.ru/flag3/index.html#http://vvl99.narod.ru/flag3/assets/img/s1200.png"></iframe></span><span><iframe src="http://vvl99.narod.ru/flag3/index.html#http://vvl99.narod.ru/flag3/assets/img/1.jpg"></iframe></span></span>`

**Comment by VVL99** [comment]
http://vvl99.narod.ru/flag3/f10x3.html

**Comment by krikienoid** [comment]
Duplicate of #21
