### ISSUE TITLE
Unable to compile in Ubuntu

### ISSUE THREAD

**Issue by lacqui** [krikienoid/flagwaver#25]
Build fails with the following message:

    [15:35:06] Error in plugin "gulp-better-rollup"
    Message:
        Could not resolve '../globals/hashStore' from src/assets/js/app/middleware/hashStoreMiddleware.js
    Details:
        code: UNRESOLVED_IMPORT`

**Comment by bryankaplan** [comment]
Please reopen. This bug is currently happening under Alpine Linux for FlagWaver 3.0.0.

**Comment by bryankaplan** [comment]
Please reopen. PR #26 has regressed in v3.0.0.

**Comment by krikienoid** [comment]
This should be fixed now.

**Comment by bryankaplan** [comment]
Thank you, @krikienoid
