### ISSUE TITLE
Flag cannot fly halfmast

### ISSUE THREAD

**Issue by mtonna257** [krikienoid/flagwaver#28]
Is it possible to "raise" and "lower" the flag, and for it to fly halfmast??

**Comment by mtonna257** [comment]
Has this project been abandoned??
My question has not been answered,

**Comment by krikienoid** [comment]
Hello there,

To answer your question, FlagWaver does not have such a feature.

**Comment by mtonna257** [comment]
Thanks... so it cannot be done. OK!
