### ISSUE TITLE
Feature Request: Weight by transparency.

### ISSUE THREAD

**Issue by GormAuslander** [krikienoid/flagwaver#30]
On [exceptionally long flags](https://i.imgur.com/f2F0HLT.png), the spring/weight gets a little whacky. I am wondering if it's possible to assign 0% weight to alpha channel portions of flags, so in the above example it would get lighter as it tapers.

A bonus would be that alpha is seen as a sort of "cutting tool", such that [flags with streamers](https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Republic_of_Venice_%281659-1675%29.svg/1024px-Flag_of_Republic_of_Venice_%281659-1675%29.svg.png) can function properly, as each streamer is seen as an independent body, anchored to the main body. I am not entirely familiar with how physics engines work so I don't know how plausible that is.

**Comment by krikienoid** [comment]
Hi there,

I think what you are suggesting is certainly possible. However actually developing such a feature is easier said than done. The spring mass model uses a simple rectangular grid, that would have to somehow be modified

**Comment by GormAuslander** [comment]
I imagine it would be more advanced in complexity, moving from a simple grid defined by image size to calculating new shapes through an alpha boolean. It's far more advanced than anything I know how to do, thus the request 🤣
