### ISSUE TITLE
Double-sided flags

### ISSUE THREAD

**Issue by Kanjilearner817** [krikienoid/flagwaver#31]
Would it be possible to make it so that double-sided flags, like the national flag of Paraguay and the state flag of Oregon, can be displayed correctly?

**Comment by Bluellama2022** [comment]
I think that should happen. However, a disadvantage would be flags having incorrect sizes on each side. Both flags **must** be the same size, and if not, the image of the obverse (but flipped) appears on the reverse, overlapped by the different reverse.

**Comment by krikienoid** [comment]
This feature is now live as of v3.0.0.
