### ISSUE TITLE
Background: Green Screen

### ISSUE THREAD

**Issue by piranha97** [krikienoid/flagwaver#39]
Hello i really like this project of yours.
I would like to suggest adding a green screen or blue screen as a selectable background, so this way every user could use his/her own background. This is also very helpful with using the flag in livestreams or videos.

**Comment by krikienoid** [comment]
Hi there, thank you for the feedback, I'll add it to the wishlist

**Comment by krikienoid** [comment]
This feature is now live as of v2.1.0.
