### ISSUE TITLE
Image could not be loaded

### ISSUE THREAD

**Issue by Robyx456** [krikienoid/flagwaver#49]
I have a problem. I try to upload an image and they don't let me load it.

**Comment by krikienoid** [comment]
What was the image?

**Comment by Robyx456** [comment]
A flag file in PNG Inviato da Posta per Windows Da: krikienoidInviato: venerdì 21 gennaio 2022 20:56A: krikienoid/flagwaverCc: Robyx456; AuthorOggetto: Re: [krikienoid/flagwaver] Image could not be loaded (Issue #49) What was the image?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>  
	
      
		Mail priva di virus. www.avast.com

**Comment by krikienoid** [comment]
Sorry but this message is not intelligible.
