### ISSUE TITLE
License

### ISSUE THREAD

**Issue by avo7** [krikienoid/flagwaver#5]
I don't see any license information anywhere in the code or on the website.

What is the code licensed under? I'd like to use it in my project, slightly modified (basically removed the controls and hardcoded the options), with an attribution of course. Can I do that?

**Comment by krikienoid** [comment]
I am okay with you using any code that I have written. However, keep in mind that this project was originally based on code from other sources that were not licensed — this was the reason I did not add a license originally — these sources are credited in the README file.
