### ISSUE TITLE
is there a way to make an http GET request to the website and set the desired image url as a header?

### ISSUE THREAD

**Issue by realmercy** [krikienoid/flagwaver#53]
trying to make a discord bot and wanted to try implementing a /flag command

**Comment by krikienoid** [comment]
Hello, FlagWaver is powered entirely by JavaScript, so there is no server you can communicate with directly. You will have to handle image hosting yourself. Once you have the image URL, generating a FlagWaver link is not difficult, just use `https://krikienoid.github.io/flagwaver/#?src=` followed by the encoded url. Hope that helps.

**Comment by realmercy** [comment]
see that is exactly i tried doing while making a /flag command for my discord bot, it goes something like 
/flag [url], where the url is the image which you want to make a flag and apparently discord cdn links don't work 
for example 
> https://cdn.discordapp.com/attachments/950071475120001086/950326376874016768/Screenshot_20220307-141453.png

this is a link to an image on my bot testing server when you click it opens a new tab and shows an image however when you do 
https://krikienoid.github.io/flagwaver/#?src=https://cdn.discordapp.com/attachments/950071475120001086/950326376874016768/Screenshot_20220307-141453.png
it shows image could not be loaded, any idea as to why it could be happening?

**Comment by krikienoid** [comment]
It looks like the image is getting blocked by the CORS policy. This is something the server that hosts the images would be responsible for.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

<img width="1217" alt="corserror" src="https://user-images.githubusercontent.com/8528227/157163673-143f6cd9-70f3-4ae6-952a-1170201a6cf2.png">
