### ISSUE TITLE
It freezes the entire browser window!

### ISSUE THREAD

**Issue by BlueHummingbird14** [krikienoid/flagwaver#56]
I've tried running FlagWaver on Microsoft Edge, but it lagged and made the entire window freeze!

**Comment by krikienoid** [comment]
Hi! Thanks for your feedback, I am not seeing an issue with Edge on my end.
I have some questions for you that might help narrow down the issue.
What version of Edge are you using? What kind of computer are you using,
and what version of Windows? Does the problem occur with the default flag
or with a specific image?

**Comment by BlueHummingbird14** [comment]
I'm using a computer running Windows 10. It might to do with the default flag...

**Comment by krikienoid** [comment]
I tested on Windows 10 and I don't see any issues on my end. If I am not
able to reproduce the issue, then there is not much I can do. If you have
any further details, please let me know.
