### ISSUE TITLE
Flag Hoisting

### ISSUE THREAD

**Issue by solomonshalom** [krikienoid/flagwaver#64]
Hey Man!

Would be cool if you can do something like this ->
![image](https://thumbs.gfycat.com/BelovedFlawedCivet-size_restricted.gif)
Basically like when a user clicks a button, it goes up in the sky

**Comment by Bluellama2022** [comment]
I think it would be cool.

**Comment by krikienoid** [comment]
Thanks for your feedback, marking this as a duplicate of #44.
