### ISSUE TITLE
Support for nonrectangular flags?

### ISSUE THREAD

**Issue by EmaBelle** [krikienoid/flagwaver#84]
I've noticed with a swallowtail design I've made that even as a png with a transparent background, the flag still moves as if it were rectangular. Is this an oversight or is it simply too difficult to program a simulation for this type of flag?

**Comment by krikienoid** [comment]
FlagWaver only creates rectangular cloth models. Being able to create custom shapes based on any image would be much more complicated to program, which is why it hasn't been done.
