### ISSUE TITLE
A button to generate "embed" HTML code?

### ISSUE THREAD

**Issue by billpg** [krikienoid/flagwaver#88]
Could there please be a button which generates some HTML that will embed the flag-waving into a website?

**Comment by krikienoid** [comment]
Hi.

You could embed it as an iframe, here is an example of what the code would look like:

`<iframe src="https://krikienoid.github.io/flagwaver/#?src=https%3A%2F%2Fi.imgur.com%2Fni7178E.png" width="600" height="400"></iframe>`
