### ISSUE TITLE
Hello krikienoid

### ISSUE THREAD

**Issue by SheepleTown** [krikienoid/flagwaver#90]
kindly, I am using the flagwaver in my project, called Sheepletown, on opensea.io . I would appreciate if you can kindly provide me with an Ethereum receiving address you have, I will please like to share the earning of the NFT sales and royalty with you. This project is so cool. You hit it right on the head with this one. Now that I see your github,, I saw that you also have created other projects (That I am eager to check once I finish this message to you).  

I am trying to figure out how to save the flagwaver with the banners I want flying. lol.
I am an author, and will soon make my novel available online. The novel includes NFTs that are part of the whole project.

Kindly please let me have your ETH receiving address in a message on twitter, mine is @thesheepletown or @sheepleone.

This is not an Issue per say but this was the only way I can communicate with you. I am new here on Github and not a developer, at all.

Waiting for your communication plz. Thx, SheepleOne

**Comment by krikienoid** [comment]
Hi, Thanks for reaching out.

I do not have an account with Twitter or Etherium, and honestly don't feel like going through the trouble of setting all that up, but thanks for offering. FlagWaver is open source and free to use, so payments of any kind are not expected or necessary. I'm glad you were able to make some cool stuff with it, best of luck with your project!

**Comment by SheepleTown** [comment]
> Hi, Thanks for reaching out.
> 
> I do not have an account with Twitter or Etherium, and honestly don't feel like going through the trouble of setting all that up, but thanks for offering. FlagWaver is open source and free to use, so payments of any kind are not expected or necessary. I'm glad you were able to make some cool stuff with it, best of luck with your project!

Oh Finally I hear from you! thanks for ur reply. I know it is free and open source, I read the project on here. Please understand that, if something good comes out of this, it must be shared somehow Bcoz its ur awesome job that made it possible. This is a part of a big project involving different things. (I do not want to sound pushy plz) So Ethereum is not a hassle, just create a trust wallet on your phone and provide me with your public address, its so simple. u never know, this collection might be very rewarding and I truly want to share. please, Do not need to make a twitter account u can just post your Ethereum public address here. Just create downland trust wallet on any smart phone u have, then create a wallet and copy paste your receiving address here, it is safe and it is only used to receive tokens and not to withdraw from, the only one that can withdraw is you, the owner. the public key on trust wallet looks something like this: 0xd92083CB89D26274751244B15996CbE58e25A29d  this is mine for example for a wallet I created, super easy. I do not want to bother you but just asking U. I hope u do it plz. btw the collection is created and can be found here using ur cool app: https://opensea.io/collection/sheepletownbanners
