### ISSUE TITLE
Very long image doesn't have long enough flagpole

### ISSUE THREAD

**Issue by DdariQ** [krikienoid/flagwaver#99]
Apologies if this isn't the best way to link it, but from mobile this image doesn't wave well.

https://www.reddit.com/r/vexillologycirclejerk/s/rpFpQdmiNf

Flag is longer than flagpole.

Thanks

**Comment by krikienoid** [comment]
I believe this is a bug with the FlagWaverBot, not with FlagWaver, it is a separate project not managed by me. The image is getting clipped by the rehosting service.

<img width="1147" alt="Screen Shot 2024-08-11 at 4 58 38 PM" src="https://github.com/user-attachments/assets/f7538003-219a-4ba6-b120-59eb665b496a">
